server {
    listen 80;
    server_name afrusculture.ru www.afrusculture.ru;

    root /var/www/afrus/current/dist;
    index index.html;

    location /.well-known/acme-challenge/ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
